MODEL_2D:
#  TYPE: "ViT-B-16"
  TYPE: "ViT-L-14"
  NUM_CLASSES: 6
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
  DUAL_HEAD: True
DATASET_TARGET:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_night",)
  VAL: ("val_night",)
  TEST: ("test_night",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/data/user2/nuscenes/nuscenes_lidarseg_intensity_preprocess/preprocess/preprocess"
    nuscenes_dir: "/data/user2/nuscenes"  # only front cam images are needed
    pselab_paths: ("/data/user1/code/UniDSeg/output/day_night/dg/UniDSeg_ViT-L-14/pselab_data/train_night.npy",)
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
#  CLASS_WEIGHTS: [1.97516268, 1., 2.10103946, 2.05838738, 1.53985452, 1.54031246]
  CLASS_WEIGHTS_PL: [2.0368557, 1., 1.95655323, 1.68931529, 1.45551211, 1.18711439]
#  CLASS_WEIGHTS_PL: [2.05898481, 1., 1.86350663, 1.75266453, 1.42940818, 1.18665661]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000

OUTPUT_DIR: "/data1/user1/code/UniDSeg/output/day_night/sfda/UniDSeg_ViT-L-14/"
